### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by Nitant2727** [Nirlep5252/codeforces-cli#1]
It will become more convenient if you such a shortcut like:
After the folder for the problem is created in directory, we write a certain command such that it opens the folder in an ide or text editor under the same problem folder name

**Comment by Nirlep5252** [comment]
ty for the suggestion.
i'll will add it in the upcoming update.

**Comment by Nirlep5252** [comment]
I have added this feature

Please update your cf version using `py -m pip install -U codeforces` 

Do test the command, and report any bugs you find.

Thank you for your suggestion, and happy coding! :)
